"use client";
import { useCallback, useEffect, useState } from "react";
import axios from "axios";
import { BarChart3, CalendarDays, Clock3, FileText, RefreshCw, Users } from "lucide-react";

const today = new Date().toISOString().slice(0, 10);
const firstDay = `${today.slice(0, 8)}01`;
const employeeName = (e) => e?.fullName || e?.employeeCode || "Employee";
const money = (n) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(n || 0);

const columns = {
  attendance: ["Employee", "Date", "Status", "Hours", "Late"],
  leaves: ["Employee", "Leave type", "From", "To", "Status"],
  payroll: ["Employee", "Month", "Net salary", "Payment", "Approved hours"],
  timesheets: ["Employee", "Date", "Project", "Hours", "Status"],
};

export default function HrReportsPage() {
  const [filters, setFilters] = useState({ startDate: firstDay, endDate: today, departmentId: "all", report: "attendance" });
  const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const token = localStorage.getItem("token"); const { data: response } = await axios.get("/api/hr/reports", { params: filters, headers: { Authorization: `Bearer ${token}` } }); setData(response.data); } catch (e) { setError(e.response?.data?.message || "Unable to load HR reports"); } finally { setLoading(false); } }, [filters.startDate, filters.endDate, filters.departmentId]);
  useEffect(() => { load(); }, [load]);
  const update = (key, value) => setFilters((f) => ({ ...f, [key]: value }));
  const rows = data?.rows?.[filters.report] || [];
  const title = filters.report === "leaves" ? "Leave" : filters.report[0].toUpperCase() + filters.report.slice(1);
  return <div className="min-h-screen bg-slate-50 px-4 py-8 sm:px-10"><div className="mx-auto max-w-7xl">
    <div className="mb-7 rounded-3xl bg-gradient-to-r from-indigo-700 to-violet-600 p-7 text-white shadow-xl shadow-indigo-100"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="mb-2 flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-indigo-100"><BarChart3 size={15} /> Human resources</p><h1 className="text-3xl font-black">HR Reports Centre</h1><p className="mt-2 text-sm text-indigo-100">Filter and review workforce performance across every HR function.</p></div><div className="rounded-xl bg-white/15 px-4 py-3 text-right"><p className="text-xs text-indigo-100">Selected period</p><p className="font-bold">{filters.startDate} — {filters.endDate}</p></div></div></div>
    <div className="mb-7 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-5"><label className="text-xs font-bold text-slate-500">From<input type="date" value={filters.startDate} max={filters.endDate} onChange={(e) => update("startDate", e.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm" /></label><label className="text-xs font-bold text-slate-500">To<input type="date" value={filters.endDate} min={filters.startDate} max={today} onChange={(e) => update("endDate", e.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm" /></label><label className="text-xs font-bold text-slate-500">Department<select value={filters.departmentId} onChange={(e) => update("departmentId", e.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm"><option value="all">All departments</option>{data?.departments?.map((d) => <option key={d._id} value={d._id}>{d.name}</option>)}</select></label><label className="text-xs font-bold text-slate-500">Report<select value={filters.report} onChange={(e) => update("report", e.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm"><option value="attendance">Attendance</option><option value="leaves">Leave</option><option value="payroll">Payroll</option><option value="timesheets">Timesheets</option></select></label><button onClick={load} className="mt-auto inline-flex items-center justify-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-bold text-white hover:bg-indigo-700"><RefreshCw size={16} /> Apply filters</button></div></div>
    {error ? <div className="rounded-2xl border border-rose-200 bg-rose-50 p-5 font-semibold text-rose-700">{error}</div> : loading ? <div className="py-20 text-center text-slate-400">Loading report data…</div> : <><div className="mb-7 grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Active employees" value={data.summary.activeEmployees} sub={`${data.summary.employees} selected`} icon={Users} color="bg-indigo-50 text-indigo-600" /><Metric label="Attendance" value={data.summary.present} sub={`${data.summary.late} late · ${data.summary.attendanceRecords} records`} icon={CalendarDays} color="bg-emerald-50 text-emerald-600" /><Metric label="Approved leaves" value={data.summary.approvedLeaves} sub={`${data.summary.leaveRequests} requests`} icon={FileText} color="bg-amber-50 text-amber-600" /><Metric label="Approved hours" value={`${data.summary.timesheetHours}h`} sub={`${data.summary.payrollCount} payroll · ${money(data.summary.payrollTotal)}`} icon={Clock3} color="bg-violet-50 text-violet-600" /></div><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-6 py-4"><h2 className="font-black text-slate-900">{title} Report</h2><p className="mt-1 text-sm text-slate-500">Filtered results · {rows.length} records shown</p></div><div className="overflow-x-auto"><ReportTable type={filters.report} rows={rows} /></div></div></>}
  </div></div>;
}
function Metric({ label, value, sub, icon: Icon, color }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex justify-between"><div><p className="text-[11px] font-black uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 text-2xl font-black text-slate-900">{value}</p><p className="mt-1 text-xs text-slate-500">{sub}</p></div><div className={`h-fit rounded-xl p-3 ${color}`}><Icon size={20} /></div></div></div>; }
function ReportTable({ type, rows }) { return <table className="w-full text-sm"><thead><tr className="bg-slate-50">{columns[type].map((c) => <th key={c} className="whitespace-nowrap px-5 py-3 text-left text-[11px] font-black uppercase tracking-wide text-slate-400">{c}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.length ? rows.map((r) => { const e = employeeName(r.employeeId); const cells = type === "attendance" ? [e, r.date, r.status, `${r.totalHours || 0}h`, r.isLate ? "Yes" : "No"] : type === "leaves" ? [e, r.leaveType, new Date(r.fromDate).toLocaleDateString(), new Date(r.toDate).toLocaleDateString(), r.status] : type === "payroll" ? [e, r.month, money(r.netSalary), r.paidStatus, `${r.approvedTimesheetHours || 0}h`] : [e, new Date(r.date).toLocaleDateString(), r.project, `${r.hours}h`, r.status]; return <tr key={r._id} className="hover:bg-indigo-50/30">{cells.map((cell, i) => <td key={i} className={`whitespace-nowrap px-5 py-3 ${i === 0 ? "font-semibold text-slate-800" : "text-slate-600"}`}>{cell}</td>)}</tr>; }) : <tr><td colSpan={columns[type].length} className="px-5 py-12 text-center text-slate-400">No records match the current filters.</td></tr>}</tbody></table>; }
