"use client";
import { useEffect, useState } from "react";

export default function CodeSeriesSettingsPage() {
  const [series, setSeries] = useState([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  const headers = () => ({ "Content-Type": "application/json", Authorization: `Bearer ${localStorage.getItem("token") || ""}` });
  const load = async () => { setLoading(true); const r = await fetch("/api/settings/code-series", { headers: headers() }); const d = await r.json(); if (d.success) setSeries(d.data); else setMessage(d.message || "Unable to load code series"); setLoading(false); };
  useEffect(() => { load(); }, []);
  const update = (index, field, value) => setSeries(current => current.map((item, i) => i === index ? { ...item, [field]: value } : item));
  const save = async () => { setSaving(true); setMessage(""); const r = await fetch("/api/settings/code-series", { method: "PUT", headers: headers(), body: JSON.stringify({ series: series.map(item => ({ ...item, nextNumber: Number(item.nextNumber) })) }) }); const d = await r.json(); setMessage(d.success ? "Code series saved." : d.message || "Could not save settings"); if (d.success) setSeries(d.data); setSaving(false); };
  return <div className="min-h-screen bg-slate-50 p-6"><div className="mx-auto max-w-5xl"><h1 className="text-2xl font-bold text-slate-900">Master Code Series</h1><p className="mt-1 text-sm text-slate-600">Set the prefix and next number. Users may still enter a valid unique code manually in master forms or imports.</p><div className="mt-6 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">{loading ? <div className="p-8 text-slate-500">Loading series…</div> : <><div className="overflow-x-auto"><table className="min-w-full"><thead className="bg-slate-50"><tr><th className="px-5 py-3 text-left text-xs font-semibold text-slate-500">MASTER</th><th className="px-5 py-3 text-left text-xs font-semibold text-slate-500">PREFIX</th><th className="px-5 py-3 text-left text-xs font-semibold text-slate-500">NEXT NUMBER</th><th className="px-5 py-3 text-left text-xs font-semibold text-slate-500">PREVIEW</th></tr></thead><tbody>{series.map((item, index) => <tr key={item.id} className="border-t border-slate-100"><td className="px-5 py-3 font-medium text-slate-800">{item.label}</td><td className="px-5 py-3"><input value={item.prefix} onChange={e => update(index, "prefix", e.target.value.toUpperCase())} className="w-32 rounded border border-slate-300 px-3 py-2 text-sm" /></td><td className="px-5 py-3"><input type="number" min="1" value={item.nextNumber} onChange={e => update(index, "nextNumber", e.target.value)} className="w-28 rounded border border-slate-300 px-3 py-2 text-sm" /></td><td className="px-5 py-3 font-mono text-sm text-indigo-700">{item.prefix || "PREFIX"}-{String(Number(item.nextNumber) || 1).padStart(4, "0")}</td></tr>)}</tbody></table></div><div className="flex items-center justify-between border-t border-slate-200 p-4"><span className="text-sm text-slate-600">{message}</span><button onClick={save} disabled={saving} className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-medium text-white disabled:opacity-50">{saving ? "Saving…" : "Save code series"}</button></div></>}</div></div></div>;
}
