import Link from "next/link";
import { ArrowRight, Boxes, CheckCircle2, ClipboardList, Factory, PackageCheck, ReceiptIndianRupee, Scissors, ShoppingCart } from "lucide-react";

const stages = [
  { no: "01", title: "Sales Order & Plan", text: "Convert approved demand into a textile production plan with item-wise specification, plant, priority and required date.", icon: ShoppingCart, links: [["Production Plans", "/admin/textiles/sales-order-integration"], ["New Plan", "/admin/textiles/sales-order-integration/new"]] },
  { no: "02", title: "Material Planning", text: "Define process-wise BOM materials and operations, then calculate shortages and procurement requirements.", icon: Boxes, links: [["Textile BOM", "/admin/textiles/bom"], ["MRP", "/admin/textiles/mrp"]] },
  { no: "03", title: "Production & Processing", text: "Track batches through weaving, greige folding, dyeing and every configured production process.", icon: Factory, links: [["Process WIP", "/admin/textiles/production/wip"], ["Weaving WIP", "/admin/textiles/production/weaving-wip"], ["Dyeing Recipes", "/admin/textiles/dyeing-recipes"]] },
  { no: "04", title: "Job Work", text: "Issue material to vendors, create challans and record finished, rejected, waste and short quantities on return.", icon: Scissors, links: [["Requests", "/admin/textiles/job-work/requests"], ["Challans", "/admin/textiles/job-work/challans"], ["Receipts", "/admin/textiles/job-work/receipts"]] },
  { no: "05", title: "Quality Inspection", text: "Inspect roll dimensions, record defects and four-point scores, then assign grade and final result.", icon: CheckCircle2, links: [["QC Inspections", "/admin/textiles/quality-inspection"], ["Defect Analytics", "/admin/textiles/quality/defect-analytics"]] },
  { no: "06", title: "Rolls, Stock & Traceability", text: "Create fabric rolls/takas, maintain rack and quality grade, and trace every batch from material to finished roll.", icon: PackageCheck, links: [["Taka / Rolls", "/admin/textiles/takas"], ["Traceability", "/admin/textiles/traceability"], ["Scan QR", "/admin/textiles/scan"]] },
  { no: "07", title: "Costing & Dispatch", text: "Calculate material, labour, machine, job-work, utility and overhead cost net of by-product recovery; prepare export documents.", icon: ReceiptIndianRupee, links: [["Production Costing", "/admin/textiles/costing"], ["Export Documents", "/admin/textiles/export-docs"], ["Reports", "/admin/textiles/reports"]] },
];

export default function TextileFlowPage() {
  return <main className="min-h-screen bg-slate-50 p-4 md:p-8"><div className="mx-auto max-w-7xl">
    <div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-indigo-600">Complete operational workflow</p><h1 className="mt-2 text-3xl font-extrabold text-slate-900">Textile Production Flow</h1><p className="mt-2 max-w-3xl text-sm text-slate-500">Sales Order → Production Plan → Material → Production / Job Work → Quality → Rolls → Costing & Dispatch</p></div><Link href="/admin/textiles/doctype" className="inline-flex items-center gap-2 rounded-xl border border-indigo-200 bg-white px-4 py-2.5 text-sm font-bold text-indigo-700"><ClipboardList size={17} />Masters & Documents</Link></div>
    <div className="grid gap-4 lg:grid-cols-2">{stages.map(({ no, title, text, icon: Icon, links }, index) => <section key={no} className="relative overflow-hidden rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start gap-4"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-indigo-50 text-indigo-600"><Icon size={22} /></span><div className="min-w-0 flex-1"><p className="text-xs font-bold tracking-widest text-indigo-500">STEP {no}</p><h2 className="mt-1 text-lg font-bold text-slate-900">{title}</h2><p className="mt-1 text-sm leading-6 text-slate-500">{text}</p><div className="mt-4 flex flex-wrap gap-2">{links.map(([label, href]) => <Link key={href} href={href} className="inline-flex items-center gap-1.5 rounded-lg bg-slate-100 px-3 py-2 text-xs font-bold text-slate-700 hover:bg-indigo-50 hover:text-indigo-700">{label}<ArrowRight size={13} /></Link>)}</div></div></div>{index < stages.length - 1 && <span className="absolute right-4 top-4 text-5xl font-black text-slate-50">{no}</span>}</section>)}</div>
  </div></main>;
}
