import Link from "next/link";
import { ArrowRight, Boxes, CheckCircle2, ClipboardList, Factory, PackageCheck, Plus, ReceiptIndianRupee, Scissors, Settings2, ShoppingCart } from "lucide-react";
import { textileDoctypes } from "@/lib/textiles/doctypeConfig";

const masters = ["fabric-specification", "yarn-specification", "color", "shade", "fabric-construction", "fiber-composition-master", "textile-process", "machine", "workstation", "cost-center", "skill", "employee-skill", "fabric-defect"];

const stages = [
  { no: "01", title: "Requirement & Sample Approval", text: "Capture the customer's fabric requirement and approve the sample, lab dip and shade before bulk planning.", icon: ShoppingCart, documents: ["customer-fabric-requirement", "sample-request", "lab-dip", "shade-approval"] },
  { no: "02", title: "Production Planning", text: "Convert approved demand into an item-wise production plan with plant, priority, quantity and required date.", icon: ClipboardList, documents: ["textile-production-plan"] },
  { no: "03", title: "Batch Creation", text: "Create the production batch that carries the item, plan, quantities, machine, operator and timings through the floor.", icon: Boxes, documents: ["production-batch"] },
  { no: "04", title: "Production & Processing", text: "Run the batch through its process route. Use the specific order where dyeing, printing or finishing needs extra details.", icon: Factory, documents: ["dyeing-recipe", "process-order", "dyeing-order", "printing-order", "finishing-order"] },
  { no: "05", title: "Job Work (when outsourced)", text: "For an outsourced process, create the order, issue material to the job worker and record the processed material on return.", icon: Scissors, documents: ["job-work-order", "job-work-material-issue", "job-work-receipt"], optional: true },
  { no: "06", title: "Quality & Rework", text: "Inspect the finished fabric, record defects and grade. Failed material can move into a controlled rework cycle.", icon: CheckCircle2, documents: ["fabric-inspection", "rework-order"] },
  { no: "07", title: "Roll, Transfer & Packing", text: "Create finished rolls, then split, transfer, reserve and pack them while preserving batch-level traceability.", icon: PackageCheck, documents: ["fabric-roll", "roll-split", "roll-transfer", "roll-packing"] },
  { no: "08", title: "Production Costing", text: "Close the cycle with actual material, labour, machine, job-work, utility and overhead cost for the batch or roll.", icon: ReceiptIndianRupee, documents: ["production-cost-sheet"] },
];

const supportingTools = [
  { group: "Planning & setup", links: [["Design Master", "/admin/textiles/designs"], ["Dyeing Recipes", "/admin/textiles/dyeing-recipes"], ["Textile BOM", "/admin/textiles/bom"], ["Shade Cards", "/admin/textiles/shade-card"], ["Quality Parameters", "/admin/textiles/quality-parameters"], ["Routings", "/admin/textiles/routings"], ["Sales Order Integration", "/admin/textiles/sales-order-integration"], ["MRP & Shortages", "/admin/textiles/mrp"]] },
  { group: "Production & job work", links: [["Process WIP", "/admin/textiles/production/wip"], ["Weaving WIP", "/admin/textiles/production/weaving-wip"], ["Greige Folding", "/admin/textiles/production/greige-folding"], ["Job Work Requests", "/admin/textiles/job-work/requests"], ["Job Work Challans", "/admin/textiles/job-work/challans"], ["Job Work Receipts", "/admin/textiles/job-work/receipts"], ["Vendor Stock", "/admin/textiles/job-work/vendor-stock"]] },
  { group: "Quality, inventory & reporting", links: [["Lot Tracking", "/admin/textiles/lot-tracking"], ["Lot Assignment", "/admin/textiles/lot-assignment"], ["Taka / Rolls", "/admin/textiles/takas"], ["QC Inspection", "/admin/textiles/quality-inspection"], ["Defect Analytics", "/admin/textiles/quality/defect-analytics"], ["Traceability", "/admin/textiles/traceability"], ["Scan QR", "/admin/textiles/scan"], ["Inventory Valuation", "/admin/textiles/inventory-valuation"], ["Production Costing", "/admin/textiles/costing"], ["Export Documents", "/admin/textiles/export-docs"], ["Supplier Performance", "/admin/textiles/supplier-performance"], ["Textile Reports", "/admin/textiles/reports"]] },
];
const listHref = (slug) => `/admin/textiles/doctype/${slug}`;
const newHref = (slug) => `/admin/textiles/doctype/${slug}/new`;

function DocumentRow({ slug, master = false }) {
  const config = textileDoctypes[slug];
  if (!config) return null;
  const canonical = config.canonicalRoute;
  const href = canonical || listHref(slug);
  return <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-100 bg-slate-50/80 p-3"><Link href={href} className="group min-w-0 flex-1"><strong className="block text-sm text-slate-800 group-hover:text-indigo-700">{config.label}</strong><span className="text-xs text-slate-400">{canonical ? `Managed in ${config.canonicalLabel}` : master ? "Reusable setup record" : "View records and current status"}</span></Link><div className="flex items-center gap-1.5"><Link href={href} className="rounded-lg px-3 py-2 text-xs font-bold text-slate-600 hover:bg-white hover:text-indigo-700">{canonical ? "Manage" : "Open"}</Link>{!canonical && <Link href={newHref(slug)} className="inline-flex items-center gap-1 rounded-lg bg-indigo-600 px-3 py-2 text-xs font-bold text-white hover:bg-indigo-700"><Plus size={13} />New</Link>}</div></div>;
}

export default function TextileFlowPage() {
  return <main className="min-h-screen bg-slate-50 p-4 md:p-8"><div className="mx-auto max-w-7xl">
    <header className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-indigo-600">DocType-based operational workflow</p><h1 className="mt-2 text-3xl font-extrabold text-slate-900">Textile Production Flow</h1><p className="mt-2 max-w-3xl text-sm text-slate-500">Requirement → Plan → Batch → Process / Job Work → Quality → Roll → Packing → Costing</p></div><Link href="/admin/textiles/doctype" className="inline-flex items-center gap-2 rounded-xl border border-indigo-200 bg-white px-4 py-2.5 text-sm font-bold text-indigo-700 hover:bg-indigo-50"><ClipboardList size={17} />All Masters & Documents</Link></header>
    <section className="mb-6 rounded-2xl border border-amber-200 bg-amber-50/70 p-5"><div className="flex items-start gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-white text-amber-600 shadow-sm"><Settings2 size={19} /></span><div className="min-w-0 flex-1"><h2 className="font-bold text-slate-900">One-time setup: create masters first</h2><p className="mt-1 text-sm text-slate-600">Transactions below use these records in their Link fields. Create each required master once, then reuse it throughout the flow.</p><div className="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{masters.map((slug) => <DocumentRow key={slug} slug={slug} master />)}</div></div></div></section>
    <div className="grid gap-4 lg:grid-cols-2">{stages.map(({ no, title, text, icon: Icon, documents, optional }) => <section key={no} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-start gap-4"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-indigo-50 text-indigo-600"><Icon size={22} /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-xs font-bold tracking-widest text-indigo-500">STEP {no}</p>{optional && <span className="rounded-full bg-amber-50 px-2 py-0.5 text-[10px] font-bold uppercase text-amber-700">Optional path</span>}</div><h2 className="mt-1 text-lg font-bold text-slate-900">{title}</h2><p className="mt-1 text-sm leading-6 text-slate-500">{text}</p></div></div><div className="space-y-2">{documents.map((slug) => <DocumentRow key={slug} slug={slug} />)}</div></section>)}</div>
    <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold text-slate-900">Supporting operational screens</h2><p className="mt-1 text-sm text-slate-500">Use these screens for planning, execution, monitoring, scanning, costing and reporting. The DocType records above remain the source documents.</p><div className="mt-5 grid gap-5 lg:grid-cols-3">{supportingTools.map(({ group, links }) => <div key={group}><h3 className="text-xs font-bold uppercase tracking-wider text-slate-400">{group}</h3><div className="mt-2 flex flex-wrap gap-2">{links.map(([label, href]) => <Link key={href} href={href} className="inline-flex items-center gap-1.5 rounded-lg bg-slate-100 px-3 py-2 text-xs font-bold text-slate-700 hover:bg-indigo-50 hover:text-indigo-700">{label}<ArrowRight size={13} /></Link>)}</div></div>)}</div></section>
  </div></main>;
}
